### PR TITLE
Added some tools

### PR DESCRIPTION
**Pull request by eugenekkh**
I added some tools to work with lists of ip addresses

### CODE REVIEW

**Comment by leth** [comment]
Very nice, thanks!
Looking at the iteration code, I don't like how it adds a mutable attribute to the instance; they don't have any other mutable state.
`IteratorAggregate` might be a cleaner interface to implement!

**Comment by eugenekkh** [comment]
Roger! So really better.

**Comment by leth** [comment]
Do you have some time to update this PR to use IteratorAggregate?

**Comment by eugenekkh** [comment]
I am new on github. I added use IteratorAggregate and make a commit. What is PR? This is Pull Request? Do I to create new pull request?

**Comment by leth** [comment]
Sorry, my mistake, you did update the Pull Request correctly, I must have missed it earlier.

**Pull request merged**
